### ISSUE TITLE
UI extension installation is broken

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#427] opened 2023-07-10 08:14 UTC
### Current Behavior

UI extension can't be installed, in version `1.1.0`. Previous version works fine.

Installation is stack in `Installing...` state and I found this error in logs:

```
k logs -n cattle-ui-plugin-system ui-plugin-operator-5d68dd4bc9-npvwl
level=error msg="error syncing 'cattle-ui-plugin-system/kubewarden': handler on-plugin-change: invalid character ':' after top-level value, requeuing"
```

I retried twice, also nightly jobs fail on this since friday.
Failed https://github.com/kubewarden/ui/actions/runs/5503375014/jobs/10028512179

**Comment by jordojordo** [comment] 2023-07-10 13:12
This will be fixed from https://github.com/rancher/ui-plugin-charts/pull/17
The issue is being caused by the incorrect endpoint for the chart when installing from the `ui-plugin-charts` repository.

**Closed by jordojordo** 2023-07-10 13:12 UTC
Labels: kind/bug
